# don't rush to take updates, but don't fall indefinitely behind,
# either. hopefully this is a reasonable compromise value?
pullRequests.frequency = "14 days"

updates.pin = [
  # Scala 2 is in maintenance mode, so it's easier to just leave the
  # build on sbt 1
  { groupId = "org.scala-sbt", artifactId = "sbt", version = "1." }
]

updates.ignore = [

  # only used internally, and they aren't ours (we aren't dogfooding
  # them), and updates are unlikely to benefit us, so there's really no
  # need to keep them current
  { groupId = "org.slf4j" },
  { groupId = "org.eclipse.jgit" },
  { groupId = "org.openjdk.jol" },

  # OSGi stuff is fragile and we suspect it is little-used,
  # so let's prefer stability
  { groupId = "biz.aQute.bnd" }

]
