############################################################-*-Makefile-*-####
# Project Configuration
##############################################################################
# $Id$

##############################################################################
# Read local configuration

-include $(ROOT)/Makefile.private

##############################################################################
# Project setup

PROJECT_NAME		?= scala
PROJECT_ROOT		?= $(ROOT)
PROJECT_BINARYDIR	?= $(PROJECT_ROOT)/bin
PROJECT_CONFIGDIR	?= $(PROJECT_ROOT)/config
PROJECT_DOCUMENTDIR	?= $(PROJECT_ROOT)/doc
PROJECT_LIBRARYDIR	?= $(PROJECT_ROOT)/lib
PROJECT_SUPPORTDIR	?= $(PROJECT_ROOT)/support
PROJECT_SOURCEDIR	?= $(PROJECT_ROOT)/sources
PROJECT_OBJECTDIR	?= $(PROJECT_ROOT)/objects
PROJECT_TESTDIR		?= $(PROJECT_ROOT)/test/files
PROJECT_DISTRIBDIR	?= $(PROJECT_ROOT)/distribs
PROJECT_ARCHIVEDIR	?= $(PROJECT_DISTRIBDIR)
PROJECT_LISTDIR		?= $(PROJECT_CONFIGDIR)/list

##############################################################################
# External libraries

# JRE
JRE_HOME		?= $(PROJECT_LIBDIR)/jre
JRE_JARFILE		?= $(JRE_HOME)/lib/rt.jar

# FJBG
FJBG_HOME		?= $(PROJECT_LIBDIR)/fjbg
FJBG_JARFILE            ?= $(FJBG_HOME)/fjbg.jar

# MSIL
MSIL_HOME		?= $(PROJECT_LIBDIR)/msil
MSIL_JARFILE		?= $(MSIL_HOME)/msil.jar
MSIL_DLLFILE		?= $(MSIL_HOME)/scala.dll
MSIL_KEYFILE		?= lamp.key

# Ant
ANT_HOME		?= $(PROJECT_LIBDIR)/ant
ANT_JARFILE		?= $(ANT_HOME)/lib/ant.jar

##############################################################################
# Standard tools

BASENAME		?= basename
BZIP2			?= bzip2
CAT			?= cat
CHMOD			?= chmod
COMM			?= comm
CP			?= cp
CVS			?= cvs
DATE			?= date
DIRNAME			?= dirname
DOS2UNIX		?= dos2unix
ECHO			?= echo
EXPR			?= expr
FIND			?= find
GREP			?= grep
GZIP			?= gzip
HEAD			?= head
INSTALL			?= $(PROJECT_SUPPORTDIR)/scripts/install
JAR			?= jar
JAVA			?= java
LN			?= ln
M4			?= m4
MD5SUM			?= md5sum
MIRROR			?= $(PROJECT_SUPPORTDIR)/scripts/mirror
MKDIR			?= mkdir
MV			?= mv
NICE			?= nice
PATCH			?= patch
RECODE			?= recode
RM			?= rm -f
SCSH			?= scsh
SED			?= sed
SORT			?= sort
STAT			?= stat
TAIL			?= tail
TAR			?= tar
TOUCH			?= touch
TR			?= tr
UNIX2DOS		?= $(RECODE) ..pc
UNZIP			?= unzip
WC			?= wc
XARGS			?= xargs
ZIP			?= zip

make			?= $(MAKE) MAKELEVEL=$(MAKELEVEL) --no-print-directory

##############################################################################
# Pico compiler

PICO			?= pico
PICO_FLAGS		?= -make -source 1.4

##############################################################################
# Scala tools

SCALA_HOME		?=
SCALA			?= $(SCALA_HOME:%=%/bin/)scala
SCALAC			?= $(SCALA_HOME:%=%/bin/)scalac
SCALAP			?= $(SCALA_HOME:%=%/bin/)scalap
SCALAINT		?= $(SCALA_HOME:%=%/bin/)scalaint
SCALARUN		?= $(SCALA_HOME:%=%/bin/)scalarun
SCALADOC		?= $(SCALA_HOME:%=%/bin/)scaladoc
SCALAINFO		?= $(SCALA_HOME:%=%/bin/)scala-info

##############################################################################
# Convert tool (ImageMagick)

CONVERT			?= convert
CONVERT_FLAGS		?=

##############################################################################
# XSLT processor

XSLTPROC		?= xsltproc
XSLTPROC_FLAGS		?=

##############################################################################
# InstallAnywhere (http://www.zerog.com/)

IA			?= build
IA_FLAGS		?=

##############################################################################
# IzPack (http://www.izforge.com/izpack/)

IZPACK			?= compile
IZPACK_FLAGS		?= -k standard

##############################################################################
# Latest files

LATEST_PREFIX		?= .latest

##############################################################################
