############################################################-*-Makefile-*-####
# Project Imports
##############################################################################
# $Id$

##############################################################################
# Read configuration

include $(ROOT)/Makefile.config

##############################################################################
# Variables

# project
PROJECT_VERSION		 = $(shell $(TAIL) -1 $(VERSION_FILE))

# version management
VERSION_FILE		 = $(PROJECT_ROOT)/VERSION
VERSION_SCRIPT		 = $(PROJECT_SUPPORTDIR)/scripts/version-manager

##############################################################################
# Makefile functions

RUN			 = $(ECHO) '$(1)'; $(1) || exit $$?
READLIST		 = $(shell $(CAT) $(1) | $(GREP) -v "^\#")

##############################################################################
# Includes

include $(PROJECT_SUPPORTDIR)/make/default.mk
include $(PROJECT_SUPPORTDIR)/make/cygwin.mk
include $(PROJECT_SUPPORTDIR)/make/exec.mk
include $(PROJECT_SUPPORTDIR)/make/grep.mk
include $(PROJECT_SUPPORTDIR)/make/wc.mk

##############################################################################
