############################################################-*-Makefile-*-####
# Project Configuration
##############################################################################
# $Id$

##############################################################################
# Read local configuration

-include $(ROOT)/Makefile.private

##############################################################################
# Project setup

PROJECT_NAME		?= scala
PROJECT_ROOT		?= $(ROOT)
PROJECT_BINARYDIR	?= $(PROJECT_ROOT)/bin
PROJECT_CONFIGDIR	?= $(PROJECT_ROOT)/config
PROJECT_DOCUMENTDIR	?= $(PROJECT_ROOT)/doc
PROJECT_LIBRARYDIR	?= $(PROJECT_ROOT)/lib
PROJECT_SUPPORTDIR	?= $(PROJECT_ROOT)/support
PROJECT_SOURCEDIR	?= $(PROJECT_ROOT)/sources
PROJECT_OUTPUTDIR	?= $(PROJECT_ROOT)/classes
PROJECT_CLASSPATH	?= $(PROJECT_OUTPUTDIR)
PROJECT_LISTDIR		?= $(PROJECT_CONFIGDIR)/list
PROJECT_APIDOCDIR	?= $(PROJECT_DOCUMENTDIR)/api

##############################################################################
# External libraries

# FJBG
FJBG_HOME		?= $(PROJECT_LIBDIR)/fjbg
FJBG_JARFILE            ?= $(FJBG_HOME)/fjbg.jar

# MSIL
MSIL_HOME		?= $(PROJECT_LIBDIR)/msil
MSIL_JARFILE		?= $(MSIL_HOME)/msil.jar

# BCEL (http://jakarta.apache.org/bcel/)
BCEL_HOME		?= $(PROJECT_LIBDIR)/bcel
BCEL_JARFILE		?= $(BCEL_HOME)/bcel.jar
BCEL_LICENSE		?= $(BCEL_HOME)/LICENSE

# XERCES (http://xml.apache.org/xerces2-j/)
XERCES_HOME		?= $(PROJECT_LIBDIR)/xerces
XERCES_JARFILE		?= $(XERCES_HOME)/xercesImpl.jar
XERCES_LICENSE		?= $(XERCES_HOME)/LICENSE

##############################################################################
# Standard tools

BASENAME		?= basename
CAT			?= cat
CHMOD			?= chmod
CP			?= cp
DATE			?= date
DIRNAME			?= dirname
ECHO			?= echo
FIND			?= find
GREP			?= grep
INSTALL			?= $(PROJECT_SUPPORTDIR)/scripts/install
JAR			?= jar
JAVA			?= java
LN			?= ln
M4			?= m4
MIRROR			?= $(PROJECT_SUPPORTDIR)/scripts/mirror
MKDIR			?= mkdir
NICE			?= nice
RECODE			?= recode
RM			?= rm -f
SCSH			?= scsh
SED			?= sed
TOUCH			?= touch
UNIX2DOS		?= $(RECODE) ..pc
WC			?= wc
XARGS			?= xargs
ZIP			?= zip

make			?= $(MAKE) MAKELEVEL=$(MAKELEVEL) --no-print-directory

##############################################################################
# Pico compiler

PICO			?= pico
PICO_FLAGS		?= -make -source 1.4

##############################################################################
# Scala compiler

SCALAC			?= $(PROJECT_BINARYDIR)/scalac
SCALADOC		?= $(PROJECT_BINARYDIR)/scaladoc

##############################################################################
# Makefile functions

RUN			?= $(ECHO) '$(1)'; $(1) || exit $$?
READLIST		?= $(shell $(CAT) $(1) | $(GREP) -v "^\#")

##############################################################################
# Includes

include $(PROJECT_SUPPORTDIR)/make/default.mk
include $(PROJECT_SUPPORTDIR)/make/cygwin.mk
include $(PROJECT_SUPPORTDIR)/make/exec.mk
include $(PROJECT_SUPPORTDIR)/make/grep.mk
include $(PROJECT_SUPPORTDIR)/make/wc.mk

##############################################################################
# Commands

cvs-fix-perms		:
	$(strip \
	    $(FIND) . -type f -perm +a=x | \
	    $(GREP) -v '.*/bin/.*' | \
	    $(XARGS) -r $(CHMOD) a-x)

.PHONY			: cvs-fix-perms

##############################################################################
