############################################################-*-Makefile-*-####
# Project Configuration
##############################################################################
# $Id$

##############################################################################
# Read local configuration

-include $(ROOT)/Makefile.private

##############################################################################
# Project setup

PROJECT_NAME		?= scala
PROJECT_ROOT		?= $(ROOT)
PROJECT_BINARYDIR	?= $(PROJECT_ROOT)/bin
PROJECT_CONFIGDIR	?= $(PROJECT_ROOT)/config
PROJECT_DOCUMENTDIR	?= $(PROJECT_ROOT)/doc
PROJECT_LIBRARYDIR	?= $(PROJECT_ROOT)/lib
PROJECT_SUPPORTDIR	?= $(PROJECT_ROOT)/support
PROJECT_SOURCEDIR	?= $(PROJECT_ROOT)/sources
PROJECT_OUTPUTDIR	?= $(PROJECT_ROOT)/classes
PROJECT_WEBSITEDIR	?= $(PROJECT_ROOT)/website
PROJECT_HTDOCSDIR	?= $(PROJECT_WEBSITEDIR)/htdocs
PROJECT_DISTRIBDIR	?= $(PROJECT_ROOT)/distribs
PROJECT_BOOTSTRAPDIR	?= $(PROJECT_ROOT)/bootstrap
PROJECT_CLASSPATH	?= $(PROJECT_OUTPUTDIR)
PROJECT_LISTDIR		?= $(PROJECT_CONFIGDIR)/list
PROJECT_APIDOCDIR	?= $(PROJECT_DOCUMENTDIR)/api

##############################################################################
# Website setup

WEBSITE_WWWROOT		?= $(shell cd "$(dir $(PROJECT_HTDOCSDIR))"; pwd)/$(notdir $(PROJECT_HTDOCSDIR))

WEBSITE_DATA_INSTALLS	?= $(WEBSITE_SOURCEDIR)/downloads/installers.xml
WEBSITE_DATA_DISTRIBS	?= $(WEBSITE_SOURCEDIR)/downloads/distrib/distributions.xml
WEBSITE_DATA_WEBINST	?= $(WEBSITE_SOURCEDIR)/downloads/webinst.xml

##############################################################################
# External libraries

# JRE
JRE_HOME		?= $(PROJECT_LIBDIR)/jre
JRE_JARFILE		?= $(JRE_HOME)/lib/rt.jar

# FJBG
FJBG_HOME		?= $(PROJECT_LIBDIR)/fjbg
FJBG_JARFILE            ?= $(FJBG_HOME)/fjbg.jar

# MSIL
MSIL_HOME		?= $(PROJECT_LIBDIR)/msil
MSIL_JARFILE		?= $(MSIL_HOME)/msil.jar

# Ant
ANT_HOME		?= $(PROJECT_LIBDIR)/ant
ANT_JARFILE		?= $(ANT_HOME)/lib/ant.jar

##############################################################################
# Standard tools

BASENAME		?= basename
BZIP2			?= bzip2
CAT			?= cat
CHMOD			?= chmod
COMM			?= comm
CP			?= cp
DATE			?= date
DIRNAME			?= dirname
ECHO			?= echo
EXPR			?= expr
FIND			?= find
GREP			?= grep
GZIP			?= gzip
HEAD			?= head
IA			?= build
INSTALL			?= $(PROJECT_SUPPORTDIR)/scripts/install
JAR			?= jar
JAVA			?= java
LN			?= ln
M4			?= m4
MIRROR			?= $(PROJECT_SUPPORTDIR)/scripts/mirror
MKDIR			?= mkdir
MV			?= mv
NICE			?= nice
RECODE			?= recode
RM			?= rm -f
SCSH			?= scsh
SED			?= sed
SORT			?= sort
STAT			?= stat
TAIL			?= tail
TAR			?= tar
TOUCH			?= touch
TR			?= tr
UNIX2DOS		?= $(RECODE) ..pc
UNZIP			?= unzip
WC			?= wc
XARGS			?= xargs
ZIP			?= zip

make			?= $(MAKE) MAKELEVEL=$(MAKELEVEL) --no-print-directory

##############################################################################
# Pico compiler

PICO			?= pico
PICO_FLAGS		?= -make -source 1.4

##############################################################################
# XSLT processor

XSLTPROC		?= xsltproc
XSLTPROC_FLAGS		?=

##############################################################################
