#!/bin/bash -x

./pull-binary-libs.sh

export ANT_OPTS="-Dfile.encoding=UTF-8 -server -XX:+AggressiveOpts -XX:+UseParNewGC -Xmx2G -Xss1M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=128M"

/home/tisue/apache-ant-1.9.6/bin/ant.bat \
  -Dstarr.version=2.11.7 \
  -Dscalac.args.optimise=-optimise \
  -Dlocker.skip=1 \
  test
