#!/bin/bash

source scripts/common

java -version
javac -version

sbtJavaCommand=(java $JAVA_OPTS "-Dsbt.ivy.home=$IVY2_DIR" -jar "$sbtLauncher" )

# setSbt takes additional arguments that are added to the `java` invocation of `$sbt`
# java arguments need to come before all program arguments (passed to sbt)
# we don't have this issue on the linux nodes, as sbt-extras handles it
function setSbt() {
  sbt=("${sbtJavaCommand[@]}" "$@" "$addJCenterCache")
}

# Build locker with STARR
setSbt
"${sbt[@]}" --warn "setupPublishCore" generateBuildCharacterPropertiesFile publishLocal

# Build quick and run the tests
parseScalaProperties buildcharacter.properties
setSbt "-Dstarr.version=$maven_version_number"
"${sbt[@]}" --warn "setupValidateTest" testAll
