/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test__ */

#ifndef _Included_Test__
#define _Included_Test__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test__
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_00024_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
