<!DOCTYPE html>
<html>
<head>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
  <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [['$','$'], ['\\(','\\)']],
      skipTags: ['script', 'noscript', 'style', 'textarea'],
      processEscapes: true
    }
  });
  </script>
  <script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

  <!-- need to use include to see value of page.chapter variable -->
  <style type="text/css">
    {% include numbering.css %}
  </style>
  <script type="text/javascript">
    // clear content of H3 nodes that start with "Example:"
    // the content is only there to determine ID of the H3 element (redcarpet doesn't let us set css id)
    $( document ).ready(function(){ $("h3[id*='example']").text("") })
  </script>

  <link rel="stylesheet" type="text/css" href="public/stylesheets/screen.css">

</head>

<body>

{{ content }}

</body>
</html>