.\" ##########################################################################
.\" #                      __                                                #
.\" #      ________ ___   / /  ___     Scala 2 On-line Manual Pages          #
.\" #     / __/ __// _ | / /  / _ |    (c) 2002-2006, LAMP/EPFL              #
.\" #   __\ \/ /__/ __ |/ /__/ __ |                                          #
.\" #  /____/\___/_/ |_/____/_/ | |    http://scala.epfl.ch/                 #
.\" #                           |/                                           #
.\" ##########################################################################
.\"
.\" Process this file with nroff -man scalaint.1
.\"
.TH scalaint 1  "April 29, 2005" "version 0.1" "USER COMMANDS"
.\"
.\" ################################# NAME ###################################
.\"
.SH NAME
scalaint \- Interpreter for the Scala 2 language
.\"
.\" ############################### SYNOPSIS #################################
.\"
.SH SYNOPSIS
\fBscalaint\fR [ <\fIsource file\fR> ]
.\"
.\" ############################### PARAMETERS ###############################
.\"
.SH PARAMETERS
.TP
<\fIsource file\fR>
One source file to be interpreted (such as MyClass.scala).
.\"
.\" ############################## DESCRIPTION ###############################
.\"
.SH DESCRIPTION
The \fBscalaint\fR tool reads class and object definitions, written in the
Scala programming language, and interprets them in an interactive shell
environment.

.\"
.\" ############################### EXAMPLES #################################
.\"
.SH EXAMPLES
.TP
Interpret a Scala program
.BR
\fBscalaint\fR HelloWorld
.\"
.\" ############################## AUTHOR(S) #################################
.\"
.SH AUTHOR
Written by Stephane Micheloud.
.\"
.\" ################################ BUGS ####################################
.\"
.SH "REPORTING BUGS"
Report bugs to <scala@listes.epfl.ch>.
.\"
.\" ############################# COPYRIGHT ##################################
.\"
.SH COPYRIGHT
Copyright \(co 2002-2006 LAMP/EPFL
.PP
This is free software; see the distribution for copying conditions.  There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" ############################## SEE ALSO ##################################
.\"
.SH "SEE ALSO"
.BR scala(1)
.\" ,
.\" .BR scalac(1),
.\" .BR scaladoc(1)
.\"
.\" ##########################################################################
.\" $Id: $
