#!/bin/sh
#XXX this script is not as smart about classpaths as it should be.
#    In particular, "scala -cp build" does not do the right
#    thing.

JAVA_DIR=/usr/share/java
LIB_CLASSPATH=$JAVA_DIR/scala-library.jar:.

exec ${JAVACMD:=java} -Xmx256M -Xms16M \
  -classpath $LIB_CLASSPATH -Dscala.boot.class.path=$SCALAC_CLASSPATH \
 "$@"
