#!/usr/bin/env bash
#
# publishes nightly build if $publish_to is set in environment.
#

[[ $# -eq 1 ]] || {
  cat <<EOM
Usage: $0 <scala version>

Environment variables:
  publish_to   rsync destination
EOM
  exit 0
}
version="$1"

[[ -d dists/archives ]] || {
  echo "Can't find build, has it completed? No directory at dists/archives"
  exit 1
}

if [[ -z $publish_to ]]; then
  echo "Nothing to publish."
else
  echo "Publishing nightly build to $publish_to"
  # Archive Scala nightly distribution
  rsync -az dists/archives/ "$publish_to/distributions"
  # only publish scaladoc nightly for trunk
  [[ $version == "master" ]] && rsync -az build/scaladoc/ "$publish_to/docs"
  # sbaz
  [[ -d dists/sbaz ]] && rsync -az dists/sbaz/ "$publish_to/sbaz"
fi
