#!/usr/bin/env bash
#
# Usage: get-scala-commit-sha [dir]
# Figures out current commit sha of a git clone.
# If no dir is given, current working dir is used.
#
# Example build version string:
#   6f1c486d0ba
#

[[ $# -eq 0 ]] || cd "$1"

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
	# printf %016s is not portable for 0-padding, has to be a digit.
	# so we're stuck disassembling it.
	hash=$(git log -1 --format="%H" HEAD)
	hash=${hash#g}
	hash=${hash:0:10}
else
	hash="unknown"
fi
echo "$hash"
