#!/usr/bin/env bash
#
# Usage: get-scala-commit-date [dir]
# Figures out current commit date of a git clone.
# If no dir is given, current working dir is used.
#
# Example build version string:
#   20120312
#

[[ $# -eq 0 ]] || cd "$1"

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
	lastcommitdate=$(git log --format="%ci" HEAD | head -n 1 | cut -d ' ' -f 1)
	lastcommithours=$(git log --format="%ci" HEAD | head -n 1 | cut -d ' ' -f 2)
else
	lastcommitdate=$(date +%Y-%m-%d)
	lastcommithours=$(date +%H:%M:%S)
fi

# 20120324
echo "${lastcommitdate//-/}-${lastcommithours//:/}"
