#!/bin/sh
#

THISDIR=`dirname $0`
ABS=${THISDIR}/abspath
LIBDIR=`$ABS $THISDIR/../lib`

cp=`${THISDIR}/cpof ${THISDIR}/../build/locker/classes`

echo ${cp}:$LIBDIR/fjbg.jar:$LIBDIR/msil.jar:$LIBDIR/forkjoin.jar:$LIBDIR/jline.jar:$LIBDIR/extra/'*'
