#!/bin/sh
#

dir=$(dirname $0)
strap="$dir/../build/strap/classes"
[[ -d $strap ]] || { echo "Error: no directory at $strap"; exit 1; }

cp=$($dir/cpof $strap)
asm=$($dir/abspath $dir/../build/asm/classes)

echo $cp:$asm
