#!/bin/bash -e -v -x

source scripts/common

sbt=("${sbt[@]}" "set resolvers in Global += \"pr-repo\" at \"$prRepoUrl\"")

case $prDryRun in

  yep)
    echo "DRY RUN"
    ;;

  *)

    # build quick using STARR built upstream, as specified by scalaVersion
    # (in that sense it's locker, since it was built with starr by that upstream job);
    # and run JUnit tests, ScalaCheck tests, partest, OSGi tests, MiMa and scaladoc
    "${sbt[@]}" \
       -Dstarr.version=$scalaVersion \
       --warn \
       "setupValidateTest $prRepoUrl" \
       $testExtraArgs \
       testAll

    ;;

esac
