/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jline_WindowsTerminal */

#ifndef _Included_jline_WindowsTerminal
#define _Included_jline_WindowsTerminal
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: term */
#undef jline_WindowsTerminal_ENABLE_LINE_INPUT
#define jline_WindowsTerminal_ENABLE_LINE_INPUT 2L
#undef jline_WindowsTerminal_ENABLE_ECHO_INPUT
#define jline_WindowsTerminal_ENABLE_ECHO_INPUT 4L
#undef jline_WindowsTerminal_ENABLE_PROCESSED_INPUT
#define jline_WindowsTerminal_ENABLE_PROCESSED_INPUT 1L
#undef jline_WindowsTerminal_ENABLE_WINDOW_INPUT
#define jline_WindowsTerminal_ENABLE_WINDOW_INPUT 8L
#undef jline_WindowsTerminal_ENABLE_MOUSE_INPUT
#define jline_WindowsTerminal_ENABLE_MOUSE_INPUT 16L
#undef jline_WindowsTerminal_ENABLE_PROCESSED_OUTPUT
#define jline_WindowsTerminal_ENABLE_PROCESSED_OUTPUT 1L
#undef jline_WindowsTerminal_ENABLE_WRAP_AT_EOL_OUTPUT
#define jline_WindowsTerminal_ENABLE_WRAP_AT_EOL_OUTPUT 2L
/*
 * Class:     jline_WindowsTerminal
 * Method:    getConsoleMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jline_WindowsTerminal_getConsoleMode
  (JNIEnv *, jobject);

/*
 * Class:     jline_WindowsTerminal
 * Method:    setConsoleMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jline_WindowsTerminal_setConsoleMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jline_WindowsTerminal
 * Method:    readByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jline_WindowsTerminal_readByte
  (JNIEnv *, jobject);

/*
 * Class:     jline_WindowsTerminal
 * Method:    getWindowsTerminalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jline_WindowsTerminal_getWindowsTerminalWidth
  (JNIEnv *, jobject);

/*
 * Class:     jline_WindowsTerminal
 * Method:    getWindowsTerminalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jline_WindowsTerminal_getWindowsTerminalHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
