name: Scala Merge CI

on:
  push:
    branches: ['2.*.x']
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build_and_test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11, 17]
    runs-on: ${{matrix.os}}
    steps:
      - run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt

      - name: Test
        run: sbt "partest run/repl-paste-parse.scala"
