
/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2002-2007, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |                                         **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*                                                                      */

// $Id$

// generated by genprod on Wed Jan 03 17:36:14 CET 2007

package scala


/** <p>
 *    Function with 6 parameters.
 *  </p>
 *
 */
trait Function6[-T1, -T2, -T3, -T4, -T5, -T6, +R] extends AnyRef {
  def apply(v1:T1, v2:T2, v3:T3, v4:T4, v5:T5, v6:T6): R
  override def toString() = "<function>"

}
